# -*- coding: utf-8 -*-
"""Data gathering and exploratory analysis Lloyd Banks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eQ1z0e0yFgLQNF76YD7fZlrCJcFLaTYC
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from google.colab import files

print("=== TAHAP 1: UPLOAD DATA EXCEL ===")
print("Silakan klik 'Choose Files' dan pilih SATU file Excel 'Customer_Churn_Data_Large.xlsx' kamu.")
# Memunculkan tombol upload
uploaded = files.upload()

if len(uploaded) == 0:
    print("❌ Upload dibatalkan. Silakan jalankan ulang cell ini.")
else:
    # Ambil nama file Excel yang baru saja di-upload
    excel_file = list(uploaded.keys())[0]
    print(f"\n✅ File '{excel_file}' berhasil di-upload!")
    print("\n=== TAHAP 2: MEMBACA 5 SHEET DARI EXCEL ===")

    # Membaca masing-masing sheet dari file Excel yang sama
    demo_df = pd.read_excel(excel_file, sheet_name='Customer_Demographics')
    trans_df = pd.read_excel(excel_file, sheet_name='Transaction_History')
    serv_df = pd.read_excel(excel_file, sheet_name='Customer_Service')
    online_df = pd.read_excel(excel_file, sheet_name='Online_Activity')
    churn_df = pd.read_excel(excel_file, sheet_name='Churn_Status')

    print("Menggabungkan kelima sheet menjadi satu data utuh...")
    df = demo_df.merge(trans_df, on='CustomerID', how='left')\
                .merge(serv_df, on='CustomerID', how='left')\
                .merge(online_df, on='CustomerID', how='left')\
                .merge(churn_df, on='CustomerID', how='left')

    # Isi data komplain CS yang kosong dengan 0
    df['InteractionID'] = df['InteractionID'].fillna(0)

    print("Merangkum transaksi per nasabah...")
    customer_df = df.groupby('CustomerID').agg(
        Age=('Age', 'first'),
        Gender=('Gender', 'first'),
        MaritalStatus=('MaritalStatus', 'first'),
        IncomeLevel=('IncomeLevel', 'first'),
        ChurnStatus=('ChurnStatus', 'first'),
        TotalTransactions=('TransactionID', 'nunique'),
        TotalSpend=('AmountSpent', 'sum'),
        AvgSpend=('AmountSpent', 'mean'),
        SupportInteractions=('InteractionID', lambda x: (x != 0).sum()),
        LoginFrequency=('LoginFrequency', 'mean'),
    ).reset_index()

    print("\nMembuat Grafik Visualisasi...")
    sns.set_theme(style="whitegrid")
    plt.figure(figsize=(6, 4))
    sns.countplot(data=customer_df, x='ChurnStatus')
    plt.title("Perbandingan Nasabah Bertahan (0) vs Churn (1)")
    plt.show()

    print("\nMembersihkan data untuk Machine Learning...")
    customer_df_encoded = pd.get_dummies(customer_df, columns=['Gender', 'MaritalStatus', 'IncomeLevel'], drop_first=True)

    num_cols = ['Age', 'TotalTransactions', 'TotalSpend', 'AvgSpend', 'SupportInteractions', 'LoginFrequency']
    scaler = StandardScaler()

    for col in num_cols:
        customer_df_encoded[col] = scaler.fit_transform(customer_df_encoded[[col]])

    # Simpan hasil akhir ke CSV agar mudah dipakai oleh AI nanti
    customer_df_encoded.to_csv("cleaned_customer_churn_data.csv", index=False)
    print("✅ SELAMAT! Data dari Excel berhasil dibersihkan dan siap digunakan untuk Machine Learning.")

import matplotlib.pyplot as plt
import seaborn as sns

print("=== MEMBUAT VISUALISASI EDA LENGKAP (DENGAN LEGEND) ===")
sns.set_theme(style="whitegrid")

# Bikin kolom sementara khusus agar teks legend-nya rapi (bukan cuma angka 0 dan 1)
plot_data = customer_df.copy()
plot_data['Label_Churn'] = plot_data['ChurnStatus'].map({0: 'Bertahan', 1: 'Pindah (Churn)'})

# 1. HISTOGRAM: Melihat Distribusi Umur Nasabah
plt.figure(figsize=(8, 5))
sns.histplot(data=plot_data, x='Age', hue='Label_Churn', multiple="stack", bins=20, palette="Set2")
plt.title("1. Histogram: Distribusi Umur Nasabah (Bertahan vs Churn)")
plt.xlabel("Umur Nasabah")
plt.ylabel("Jumlah Nasabah")
plt.show()

# 2. BOX PLOT: Melihat Anomali/Outlier pada Rata-rata Pengeluaran
plt.figure(figsize=(8, 5))
sns.boxplot(data=plot_data, x='Label_Churn', y='AvgSpend', palette="Set1")
plt.title("2. Box Plot: Rata-rata Pengeluaran per Bulan berdasar Status Churn")
plt.xlabel("Status Nasabah")
plt.ylabel("Rata-rata Pengeluaran ($)")
plt.show()

# 3. BAR CHART: Hubungan Tingkat Pendapatan dengan Churn
plt.figure(figsize=(8, 5))
sns.countplot(data=plot_data, x='IncomeLevel', hue='Label_Churn', palette="Paired", order=['Low', 'Medium', 'High'])
plt.title("3. Bar Chart: Tingkat Churn Berdasarkan Level Pendapatan")
plt.xlabel("Tingkat Pendapatan")
plt.ylabel("Jumlah Nasabah")
# Memaksa legend untuk tampil di posisi yang paling pas
plt.legend(title='Keterangan', loc='upper right')
plt.show()

# 4. SCATTER PLOT / HEATMAP: Melihat Korelasi (Hubungan antar angka)
plt.figure(figsize=(8, 6))
# Hanya mengambil kolom yang berisi angka
kolom_angka = ['Age', 'TotalTransactions', 'TotalSpend', 'AvgSpend', 'SupportInteractions', 'LoginFrequency', 'ChurnStatus']
korelasi = customer_df[kolom_angka].corr()

sns.heatmap(korelasi, annot=True, cmap="coolwarm", fmt=".2f", linewidths=.5)
plt.title("4. Heatmap: Korelasi Antar Faktor Perilaku Nasabah")
plt.show()

print("✅ Selesai! Semua grafik sekarang sudah dilengkapi dengan Legend yang jelas.")

